/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Assignment {
  company_id: string;
  created_at: Generated<Timestamp>;
  employment_id: string;
  id: Generated<string>;
  job_title: string;
  org_unit_id: string;
  site_id: string | null;
  valid: string;
}

export interface AuditChangeLog {
  actor_user_id: string | null;
  after: Json | null;
  at: Generated<Timestamp>;
  before: Json | null;
  changed: string[];
  company_id: string;
  id: Generated<Int8>;
  op: string;
  request_id: string | null;
  row_id: string | null;
  table_name: string;
}

export interface AuditEvent {
  actor_user_id: string | null;
  at: Generated<Timestamp>;
  company_id: string | null;
  data: Generated<Json>;
  id: Generated<Int8>;
  request_id: string | null;
  subject_id: string | null;
  subject_type: string | null;
  type: string;
}

export interface AuditMaskedColumn {
  column_name: string;
  table_name: string;
}

export interface Company {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface Employment {
  company_id: string;
  created_at: Generated<Timestamp>;
  end_date: Timestamp | null;
  end_reason: string | null;
  hire_date: Timestamp;
  id: Generated<string>;
  matricule: string;
  matricule_search: Generated<string | null>;
  person_id: string;
}

export interface EmploymentSalary {
  base_salary: Numeric;
  company_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  employment_id: string;
  id: Generated<string>;
  valid: string;
}

export interface OrgUnit {
  axis: Generated<string>;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_root: Generated<boolean>;
  kind: string;
}

export interface OrgUnitClosure {
  ancestor_id: string;
  company_id: string;
  depth: number;
  descendant_id: string;
}

export interface OrgUnitKind {
  code: string;
  is_root: Generated<boolean>;
  label_ar: string;
  label_en: string;
  label_fr: string;
  sort_order: number;
}

export interface OrgUnitKindParent {
  kind: string;
  parent_kind: string;
}

export interface OrgUnitVersion {
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  name_ar: string | null;
  name_search: Generated<string | null>;
  org_unit_id: string;
  parent_id: string | null;
  site_id: string | null;
  valid: string;
}

export interface Permission {
  code: string;
  group_code: string;
  label_ar: string;
  label_en: string;
  label_fr: string;
  sensitive: Generated<boolean>;
  sort_order: number;
}

export interface Person {
  birth_date: Timestamp | null;
  birth_place: string | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  first_name: string;
  first_name_ar: string | null;
  id: Generated<string>;
  last_name: string;
  last_name_ar: string | null;
  nationality: Generated<string>;
  nin: string | null;
  search_text: Generated<string | null>;
  sex: string | null;
  sort_name: Generated<string | null>;
}

export interface PersonSensitive {
  bank_name: string | null;
  company_id: string;
  nss: string | null;
  person_id: string;
  rib: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Role {
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_system: Generated<boolean>;
  name_ar: string;
  name_en: string;
  name_fr: string;
}

export interface RoleGrant {
  company_id: string;
  ended_at: Timestamp | null;
  ended_by: string | null;
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  id: Generated<string>;
  include_descendants: Generated<boolean>;
  org_unit_id: string;
  role_id: string;
  user_id: string;
  valid: Generated<string | null>;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
}

export interface RolePermission {
  company_id: string;
  permission_code: string;
  role_id: string;
}

export interface Site {
  address: string | null;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  wilaya: string;
}

export interface DB {
  assignment: Assignment;
  "audit.change_log": AuditChangeLog;
  "audit.event": AuditEvent;
  "audit.masked_column": AuditMaskedColumn;
  company: Company;
  employment: Employment;
  employment_salary: EmploymentSalary;
  org_unit: OrgUnit;
  org_unit_closure: OrgUnitClosure;
  org_unit_kind: OrgUnitKind;
  org_unit_kind_parent: OrgUnitKindParent;
  org_unit_version: OrgUnitVersion;
  permission: Permission;
  person: Person;
  person_sensitive: PersonSensitive;
  role: Role;
  role_grant: RoleGrant;
  role_permission: RolePermission;
  site: Site;
}
