/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Company {
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface OrgUnit {
  axis: Generated<string>;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_root: Generated<boolean>;
  kind: string;
}

export interface OrgUnitClosure {
  ancestor_id: string;
  company_id: string;
  depth: number;
  descendant_id: string;
}

export interface OrgUnitKind {
  code: string;
  is_root: Generated<boolean>;
  label_ar: string;
  label_en: string;
  label_fr: string;
  sort_order: number;
}

export interface OrgUnitKindParent {
  kind: string;
  parent_kind: string;
}

export interface OrgUnitVersion {
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  name_search: Generated<string | null>;
  org_unit_id: string;
  parent_id: string | null;
  site_id: string | null;
  valid: string;
}

export interface Permission {
  code: string;
  group_code: string;
  label_ar: string;
  label_en: string;
  label_fr: string;
  sensitive: Generated<boolean>;
  sort_order: number;
}

export interface Role {
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_system: Generated<boolean>;
  name_ar: string;
  name_en: string;
  name_fr: string;
}

export interface RoleGrant {
  company_id: string;
  ended_at: Timestamp | null;
  ended_by: string | null;
  granted_at: Generated<Timestamp>;
  granted_by: string | null;
  id: Generated<string>;
  include_descendants: Generated<boolean>;
  org_unit_id: string;
  role_id: string;
  user_id: string;
  valid: Generated<string | null>;
  valid_from: Timestamp;
  valid_to: Timestamp | null;
}

export interface RolePermission {
  company_id: string;
  permission_code: string;
  role_id: string;
}

export interface Site {
  address: string | null;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  wilaya: string;
}

export interface DB {
  company: Company;
  org_unit: OrgUnit;
  org_unit_closure: OrgUnitClosure;
  org_unit_kind: OrgUnitKind;
  org_unit_kind_parent: OrgUnitKindParent;
  org_unit_version: OrgUnitVersion;
  permission: Permission;
  role: Role;
  role_grant: RoleGrant;
  role_permission: RolePermission;
  site: Site;
}
