/**
 * Two-step sign-in (TOTP) types — `docs/contracts/mfa.md` › Endpoints. Plain TypeScript, no Angular.
 * Field names match the contract text exactly.
 */

/** `GET /api/me/mfa`. */
export interface MfaStatus {
  readonly enabled: boolean;
  readonly required: boolean;
  /** ISO timestamp of activation; `null` while off. */
  readonly enrolledAt: string | null;
  readonly recoveryCodesLeft: number | null;
}

/** `POST /api/me/mfa/enroll/start` → a new PENDING secret (replaces a previous pending one). */
export interface MfaEnrollment {
  /** Base32 (no padding): what the user types when they cannot scan. */
  readonly secret: string;
  /** `otpauth://totp/HRForce:<email>?secret=…&issuer=HRForce` — what the QR code encodes. */
  readonly otpauthUri: string;
  /** The QR code as a PNG data URL (`data:image/png;base64,…`), generated by the API. */
  readonly qrPng: string;
}

/** `POST /api/me/mfa/enroll/confirm` and `POST /api/me/mfa/recovery-codes` → the new codes, shown ONCE. */
export interface RecoveryCodes {
  readonly recoveryCodes: readonly string[];
}

/** Body of confirm / recovery-codes / disable: the current authenticator code. */
export interface MfaCode {
  readonly code: string;
}
